wavesplatform/WavesGUI

js/waves.ui.js, tests/SpecRunner.html
=> fixed wrong call to Waves.sign()

3RD-PARTY-LICENSES.txt, index.html, js/3rdparty/combodate.js, js/waves.ui.js, js/waves.util.js
Adding combodate JS, MIT license
Applying to history Tab to start for search queries
=> combodate, transaction querys

css/style.css, index.html
=> Added style to the SELECT fields in History Tab

css/style.css, index.html
- Eliminated tint div and its CSS rules
- Applied tint directly on background image via CSS gradient
=> Fix for scrolling problems at login

index.html, js/waves.ui.functions.js
=> Changed transition from Login to Client areas via JQ

index.html, js/waves.api.address.js, js/waves.api.js, js/waves.constants.js, js/waves.ui.functions.js, js/waves.ui.js, js/waves.ui.lockscreen.js, js/waves.ui.wallet.js, tests/SpecRunner.html, tests/spec/waves.address.spec.js, tests/spec/waves.util.spec.js
Added 1w prefix to address when it's displayed to a user. When address is sent to backend 1w prefix is stripped
=> Address is now prefixed with '1w'

js/waves.ui.lockscreen.js
Should be AND instead of OR, or it will evalutate true even in case of currentAccounts is null.
=> Changed condition

index.html, js/waves.api.address.js, js/waves.ui.js, js/waves.ui.lockscreen.js, tests/spec/waves.address.spec.js
Password is now validated to require strength.
Field values checks replaced with jquery validation engine.
=> Added validation to import/create account form

js/waves.ui.functions.js
=> Fixed issues on loading testnet addresses from browser storage

js/waves.api.address.js, js/waves.constants.js
Moved address factory/validation methods to a separate entity.
Class WaveAddress is now quite simple as it should be.
=> Addresses reimplemented 

index.html, js/waves.ui.js
=> Added a backup modal

index.html
Pretty simple, just wanted to contribute really :smile:
=> Fix typo in new account notice dialog

index.html
Removed annoying tooltip that hangs after new account notice dialog is closed.
=> Removed annoying tooltip

index.html, js/waves.constants.js, js/waves.ui.functions.js, js/waves.ui.wallet.js, js/waves.util.js, tests/SpecRunner.html, tests/spec/waves.util.spec.js
Fixed commission is now equal to 0.001 waves
Added methods to convert from waves to wavelets and back. Definitely need a money class for waves.
Added some tests.
=> Increased transaction fee to 0.001 waves

index.html, js/waves.constants.js, js/waves.money.js, js/waves.ui.functions.js, js/waves.ui.js, js/waves.ui.lockscreen.js, js/waves.ui.wallet.js, js/waves.util.js, tests/SpecRunner.html, tests/spec/waves.money.spec.js, tests/spec/waves.util.spec.js
Refactored transaction table building code. Removed tons of duplicate lines.
=> Fixed issues with self payments.

js/3rdparty/jquery.modal.js
Used the solution from here https://github.com/josh7up/jquery-modal/commit/ebb849c36218b8f467ddf23fd8b99b5612997736
=> fix(modals): Modals haven't been closed if opened on doubleclick

js/waves.ui.wallet.js
=> Fixed a bug when a tx fee hasn't been propagated to the send method

src/js/navigation/tab.directive.js, src/js/portfolio/asset.details.controller.js, src/js/shared/dialog.service.js
Nasty bug led to showing outdated information on popups
=> fix(modal): jquery modal pollutes document with copies of modal dialog divs

src/index.html, src/js/tokens/token.create.controller.js
=> Changed non-reissuable asset warning text

src/js/home.controller.js, src/js/portfolio/mass.payment.controller.js
=> Fixed chrome extension logout again.

src/js/portfolio/mass.payment.controller.js
Also decreased maximum mass payment file size to 512Kb
=> Added a limitation for payments per file for mass payment

Gruntfile.js, src/js/wallet/wallet.deposit.controller.js, src/js/wallet/wallet.withdraw.controller.js
Also added simple error handling in the withdraw and deposit controllers.
=> Added shorthand functions in Gruntfile.js

src/less/tab-wallet.less
Taiga issue #581 (https://tree.taiga.io/project/alexeykiselev-waves-full-node/issue/581)
=> Fixed transactions typesetting

src/less/dex/component.less, src/templates/dex/component.html
=> Removed support mention

.jshintrc, src/js/dex/component.js, src/js/dex/order.creator.component.js, src/js/dex/orderbook.component.js, src/less/dex/orderbook.component.less, src/templates/dex/component.html, src/templates/dex/order.creator.component.html, src/templates/dex/orderbook.component.html
Changed the way total is calculated in different cases
Fixed precisions in orderbook
Small styling fixes
=> Added clicks on orderbook rows triggering order form completion

src/js/dex/component.js, src/js/dex/order.service.js, src/js/dex/user.orders.component.js, src/less/dex/user.orders.component.less, src/templates/dex/user.orders.component.html
Fixed the case with the last order missed if statements
=> Changed order storage format

src/js/dex/asset.picker.component.js, src/js/dex/component.js, src/js/shared/assets.store.factory.js
Fixed a bug when an asset name filled the input every 5 seconds
=> Added traded assets from matcher to DEX

Gruntfile.js, bower.json, package.json, src/desktop/package.json, src/index.html, src/js/app.js, src/js/dex/chart.component.js, src/js/dex/charts.factory.js, src/js/dex/component.js, src/js/dex/history.component.js, src/js/dex/order.creator.component.js, src/less/dex/history.component.less, src/less/dex/order.creator.component.less, src/less/shared/typographic.less, src/templates/dex/component.html, src/templates/dex/order.creator.component.html
Also, displayed data are wiped when the pair is changed.
=> Tradable and clickable balance on DEX

bower.json, package.json, src/desktop/package.json, src/js/dex/component.js, src/js/portfolio/asset.list.controller.js, src/js/shared/transaction.filter.js, src/js/shared/transaction.menu.component.js, src/js/wallet/card.deposit.controller.js, src/templates/dex/component.html, src/templates/shared/transaction.history.component.html
Increased deposit amount limits for Coinomat
Added fee asset to Full TX Info
Added a note about non-verified assets in DEX
=> Quick fixes

src/js/shared/transaction.filter.js
in functions getFeeAsset and formatFee, changed transaction.feeAssetId to transaction.feeAsset since feeAssetId doesn't exists. It's was showing all assetfee's as WAVES that used 8 decimals (WAVES precision)
=> fixed feeAsset transaction display for transactions

src/modules/ui/directives/leftMenu/leftMenu.less
=> client-273: leftMenuIconsBugFixAndPixPerfect

src/modules/utils/modals/settings/settings.less
fixed settings modal window width
=> client-292-release-settings-width: settings modal min-width fix

src/modules/dex/directives/layout/layout.less, src/modules/ui/directives/button/button.less
=> client-292-release-settings-width: dex-layout-arrows-fix

src/modules/dex/directives/layout/layout.less
=> Client 410 dex collapse

src/modules/utils/directives/validators/Validate.js
- Changed the way input element limits allowed symbols.
=> CLIENT-611: fix numeric input in Firefox browser

src/index.html, src/modules/utils/modals/changeToken/TokenChangeModalCtrl.js, src/modules/utils/modals/changeToken/change-token-modal.html
Wrong upper limit of the reissue amount calculation is fixed.
=> CLIENT-828: change error message for exceeding allowed amount for tokens reissue

src/modules/ui/directives/actions/Actions.js, src/modules/ui/directives/actions/actions.html, src/modules/ui/directives/actions/actions.less
=> CLIENT-720: open Actions drop-down up when there is no place to show it below

package.json
=> CLIENT-1293: Up version

src/modules/utils/modals/ModalManager.js, src/modules/utils/modals/sendAsset/AssetSendCtrl.js
Added attachment parameter to AssetSendCtrl. It's usefull for Payment API.
=> Added attachment parameter

src/modules/ui/directives/transaction/Transaction.js
Reverts wavesplatform/WavesGUI#1090
=> Revert "CLIENT-1571: sposnored fee is not spam"

src/modules/ui/directives/transaction/Transaction.js
Reverts wavesplatform/WavesGUI#1097
=> Revert "Revert "CLIENT-1571: sposnored fee is not spam""

src/img/icons/flags/de.svg, src/img/icons/flags/est.svg, src/img/icons/flags/fr.svg, src/img/icons/flags/id.svg, src/img/icons/flags/it.svg, src/modules/ui/directives/changeLanguage/changeLanguage.less, ts-scripts/meta.json
При выборе французского и эстонского, остаётся английский язык.
=> CLIENT-1450: add langs: it, de, id, fr, est

src/modules/dex/controllers/DexCtrl.js, src/modules/dex/directives/dexWatchlist/WatchList.js
Не уверен, что так работать с title хорошая практика.
=> CLIENT-1629: pair rate in title

Jenkinsfile
1. Added one more parameter 'deleted' to parse and filter from WebHook
2. Added **Discard build** policy
3. Removed **if env.JOB_NAME.contains('Waves/Waves')** kostyl' - no longer needed.
=> Dont build on branch remove

Jenkinsfile
1. Container info was incorrect because images are being created in parallel and I wrote info to the same variable. Switching to map should address it. Also, I've added GIT parameters too early.
2. Removed needless try-catch-finally blocks. Because of them it looks like here are a lot of changes. Actually - no.
=> Container info fix

src/index.hbs, src/modules/app/app.js, src/modules/desktopUpdate/controllers/DesktopUpdateCtrl.js, src/modules/desktopUpdate/desktopUpdate.js, src/modules/desktopUpdate/templates/desktopUpdate.html
depends on branch https://github.com/wavesplatform/WavesGUI/tree/electron-download
=> DEXW-2281: Update desktop wizard
